name: Build & Deploy Tech Radar

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate-and-build:
    name: Validate & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Validate blip schemas
        run: npm run validate
        continue-on-error: true  # Don't fail build on validation warnings

      - name: Build radar
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Upload build artifact (for PR preview)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tech-radar-pr-${{ github.event.pull_request.number }}
          path: ./dist
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    needs: validate-and-build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  comment-pr:
    name: Comment on PR
    needs: validate-and-build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            const body = `## 🎯 Tech Radar Preview Built

            Your changes have been built successfully!

            📦 **Download the preview:**
            - Visit the [workflow run](${artifactUrl})
            - Download the \`tech-radar-pr-${prNumber}\` artifact
            - Extract and open \`index.html\` in your browser

            💡 **Tip:** After this PR merges, the radar will be automatically deployed to GitHub Pages.

            <sub>Generated by Tech Radar CI</sub>`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body
            });
